### ISSUE TITLE
No module named 'yt_dlp'

### ISSUE THREAD

**Issue by timrhaynes** [glubsy/livestream_saver#69]
I have been using livestream_saver successfully for months, with a nightly cron job that kills the process, does a git pull to get latest, and starts the livestream_saver process again.

For the past week, it has failed to download the monitored stream several times. Running it manually, I get this error now:
Traceback (most recent call last):
  File "/home/trhaynes/livestream_saver/livestream_saver.py", line 16, in <module>
    from livestream_saver.download import YoutubeLiveStream
  File "/home/trhaynes/livestream_saver/livestream_saver/download.py", line 26, in <module>
    from livestream_saver.request import YoutubeUrllibSession
  File "/home/trhaynes/livestream_saver/livestream_saver/request.py", line 16, in <module>
    from yt_dlp.extractor.youtube import INNERTUBE_CLIENTS
ModuleNotFoundError: No module named 'yt_dlp'

I have done a 'pip3 install --upgrade yt_dlp' successfully, but still get this error. 
I did a 'sudo apt-get update' and 'sudo apt-get upgrade' and still get this error.

Any advice on how I can fix this issue? Thank you!

**Comment by glubsy** [comment]
You should use a virtual environment and install the dependencies there (with `pip install -r requirements.txt`). But if you prefer using system-wide libraries, then the solution to your issue is to do `sudo pip3 install --upgrade yt_dlp` since you are invoking the system-wide pip3 (otherwise the libs will be installed in your /home/user directory).

Note that this program is broken right now, you won't be able to do much apart from maybe triggering hooks in 
 monitor mode. Use yt-dlp to download instead. I will update the Readme.md accordingly.

**Comment by timrhaynes** [comment]
I am running it in a virtual environment, already.
When you say "this program is broken right now" do you mean livestream_saver itself is broken, or that yt-dlp is broken? I assume the former, but wanted to confirm.
